# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b769d185653b7cb6b04f14dc602c24f447ca16bd1da8e643f3028646fa24f9e3feb2e270c0961e25046293be90d0cf2ff66d6abea365cc8ff44924994233b5ad

test:
  secret_key_base: 23bf276fa56139f8313cd72c4c58824e3038caa4dd5d422c133ed2e2e22d9d90b1df96113fe8ee35072925e3af2c1ec26efa6cb2ec9928109bc096929f5ef6d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
